### PR TITLE
document authorization concept

### PR DESCRIPTION
**Pull request by annashamray**

### CODE REVIEW

**Review by svenvandescheur — APPROVED** [review]
Turned out to of good assistance, so works as intended 👍

**Review by damm89 — APPROVED** [review]
Nicely put together. I have two questions:

1) Don't we also have "Report"/"SearchReport" permissions or did I implement it wrong and will it be changed sometime?
2) I think the arrows in the picture of the relationships point the wrong way, unless there's some convention I'm unaware of. For example, the accounts_blueprintpermission and accounts_authorizationprofile are required to create accounts_authorizationprofile_blueprint_permissions, right?

**Comment by sergei-maertens** [comment]
@damm89 don't think it's wrong, but rather incomplete - let's update the documentation with the extra permissions!

**Review by sergei-maertens — APPROVED** [review]

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
Please update the relations image (last one) with the refactored dates :grimacing:

**Review by kelvincy — APPROVED** [review]

**Comment by annashamray** [comment]
@sergei-maertens 
ER diagram is updated

@damm89 
1. I've missed that the report permissions were created. I've added them to the doc now.
2. I use PyCharm to generate ER diagram, if it confuses more than it helps I can just remove it

**Comment by damm89** [comment]
> I've missed that the report permissions were created. I've added them to the doc now.

No, no need to remove. They definitely help. :+1:

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
